In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import ipywidgets as widgets
%matplotlib inline
from IPython.display import display
%matplotlib notebook

Models = ['GRU','SRNN (16 1)', 'SRNN (8 2)', 'SRNN (4 3)', 'SRNN (2 8)', 'DCCNN']
Dataset = ['Yelp 2013', 'Yelp 2014', 'Yelp 2015', 'Yelp_P', 'Amazon_F', 'Amazon_P']

def myplot_dataset(dataset,model):
    data = pd.read_csv('srnn_data.csv')
    data.index = data.Dataset
    data = data.drop(['Dataset'],axis = 1)
    #l = list(dataset)
    #print(l)
    mydata = data[data.Model == model].loc[list(dataset)]
    mydata.drop(columns='Model', inplace=True)
    mydata = mydata.transpose()
    #print(mydata)
    mydata.plot.bar()
        
    
def myplot_model(model, dataset):
    data = pd.read_csv('srnn_data.csv')
    data.index = data.Model
    data = data.drop(['Model'],axis = 1)
    #dataset_index = Dataset[dataset.index]
    mydata = data[data.Dataset == dataset].loc[list(model)]
    mydata.drop(columns='Dataset', inplace=True)
    mydata = mydata.transpose()
    mydata.plot.bar()
    #plt.figure(figsize=(10,6))
    
def choice(select):
    if select== 'Dataset':
        dataset = widgets.SelectMultiple(options=Dataset, value=['Yelp 2013'], rows=6, description='Dataset')
        model = widgets.RadioButtons(options=Models, description='Models')
        i=widgets.HBox([ model, dataset])
        out = widgets.interactive_output(myplot_dataset, {'dataset':dataset ,'model':model})
        display(i,out)
    else:
        dataset = widgets.RadioButtons(options=Dataset, description='Dataset')
        model = widgets.SelectMultiple(options=Models, value=['GRU'], rows=6, description='Models')
        i=widgets.HBox([dataset, model])
        out = widgets.interactive_output(myplot_model, {'model':model, 'dataset':dataset})
        display(i,out)

select = widgets.RadioButtons(options=['Dataset', 'Model'], description='Select:')
widgets.interactive(choice, select = select)

interactive(children=(RadioButtons(description='Select:', options=('Dataset', 'Model'), value='Dataset'), Outpâ€¦

In [3]:
data = pd.read_csv('srnn_data.csv')
data

      Dataset        Model  Parameters  Validation   Test  Time/Epoch
0   Yelp 2013          GRU        5.76       66.56  66.12        3172
1   Yelp 2013  SRNN (16 1)        5.77       67.18  67.03         270
2   Yelp 2013   SRNN (8 2)        5.79       67.11  66.80         145
3   Yelp 2013   SRNN (4 3)        5.80       67.26  66.72         164
4   Yelp 2013   SRNN (2 8)        5.85       66.30  66.41         204
5   Yelp 2013        DCCNN        5.78       64.91  64.79          67
6   Yelp 2014          GRU        5.76       70.37  70.63        4142
7   Yelp 2014  SRNN (16 1)        5.77       70.53  70.70         388
8   Yelp 2014   SRNN (8 2)        5.79       70.35  70.76         201
9   Yelp 2014   SRNN (4 3)        5.80       70.25  70.48         238
10  Yelp 2014   SRNN (2 8)        5.85       69.50  69.70         284
11  Yelp 2014        DCCNN        5.78       68.46  68.66          96
12  Yelp 2015          GRU        5.76       72.52  72.89        4434
13  Yelp 2015  SRNN (16 1)        5.77       73.09  73.50         510
14  Yelp 2015   SRNN (8 2)        5.79       72.84  73.30         319
15  Yelp 2015   SRNN (4 3)        5.80       72.98  73.29         309
16  Yelp 2015   SRNN (2 8)        5.85       72.37  72.75         367
17  Yelp 2015        DCCNN        5.78       70.69  70.94         131
18     Yelp_P          GRU        5.76       96.02  95.96        3170
19     Yelp_P  SRNN (16 1)        5.77       95.83  95.92         401
20     Yelp_P   SRNN (8 2)        5.79       95.87  95.99         205
21     Yelp_P   SRNN (4 3)        5.80       95.90  96.04         236
22     Yelp_P   SRNN (2 8)        5.85       95.69  95.88         297
23     Yelp_P        DCCNN        5.78       95.03  95.26          98
24   Amazon_F          GRU        5.76       61.54  61.36        8953
25   Amazon_F  SRNN (16 1)        5.77       61.65  61.65        1584
26   Amazon_F   SRNN (8 2)        5.79       61.58  61.41        1147
27   Amazon_F   SRNN (4 3)        5.80       61.50  61.40        1166
28   Amazon_F   SRNN (2 7)        5.85       61.04  60.88        1344
29   Amazon_F        DCCNN        5.78       59.64  59.60         401
30   Amazon_P          GRU        5.76       95.27  95.22       11062
31   Amazon_P  SRNN (16 1)        5.77       95.29  95.26        2144
32   Amazon_P   SRNN (8 2)        5.79       95.21  95.18        1309
33   Amazon_P   SRNN (4 3)        5.80       95.12  95.12        1567
34   Amazon_P   SRNN (2 7)        5.85       94.98  95.02        1886
35   Amazon_P        DCCNN        5.78       94.72  94.69         448